apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildings-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildings-monitor
  template:
    metadata:
      labels:
        app: buildings-monitor
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.28
          env:
            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: digital-twin-config
                  key: KAFKA_PORT
          command: ['sh', '-c', 'until nc -z kafka $KAFKA_PORT; do echo waiting for kafka; sleep 2; done;']
        - name: wait-for-influxdb
          image: busybox:1.28
          env:
            - name: INFLUXDB_PORT
              valueFrom:
                configMapKeyRef:
                  name: digital-twin-config
                  key: INFLUXDB_PORT
          command: ['sh', '-c', 'until nc -z influxdb $INFLUXDB_PORT; do echo waiting for influxdb; sleep 2; done;']
      containers:
        - name: buildings-monitor
          image: digital-twin/buildings-monitor:latest
          imagePullPolicy: Never
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: digital-twin-config
                  key: KAFKA_BROKERS
            - name: KAFKA_TOPIC_BUILDINGS
              valueFrom:
                configMapKeyRef:
                  name: digital-twin-config
                  key: KAFKA_TOPIC_BUILDINGS
            - name: KAFKA_GROUP_ID
              value: "buildings-monitor-group"
            - name: INFLUXDB_URL
              valueFrom:
                configMapKeyRef:
                  name: digital-twin-config
                  key: INFLUXDB_URL
            - name: INFLUXDB_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: digital-twin-config
                  key: INFLUXDB_TOKEN
            - name: INFLUXDB_ORG
              valueFrom:
                configMapKeyRef:
                  name: digital-twin-config
                  key: INFLUXDB_ORG
            - name: INFLUXDB_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: digital-twin-config
                  key: INFLUXDB_BUCKET_BUILDINGS
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
