apiVersion: v1
kind: Service
metadata:
  name: notification-manager
spec:
  type: ClusterIP
  selector:
    app: notification-manager
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-manager
  template:
    metadata:
      labels:
        app: notification-manager
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.28
          env:
            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: digital-twin-config
                  key: KAFKA_PORT
          command: ['sh', '-c', 'until nc -z kafka $KAFKA_PORT; do echo waiting for kafka; sleep 2; done;']
        - name: wait-for-mongodb-notifications
          image: busybox:1.28
          env:
            - name: MONGODB_PORT
              valueFrom:
                configMapKeyRef:
                  name: digital-twin-config
                  key: MONGODB_PORT
          command: ['sh', '-c', 'until nc -z mongodb-notifications $MONGODB_PORT; do echo waiting for mongodb-notifications; sleep 2; done;']
      containers:
        - name: notification-manager
          image: digital-twin/notification-manager:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: digital-twin-config
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: digital-twin-config
                  key: MONGODB_URI_NOTIFICATIONS
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: digital-twin-config
                  key: MONGODB_DATABASE_NOTIFICATIONS
            - name: KAFKA_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: digital-twin-config
                  key: KAFKA_GROUP_ID_NOTIFICATIONS
            - name: KAFKA_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: digital-twin-config
                  key: KAFKA_CLIENT_ID_NOTIFICATIONS
            - name: API_PORT
              value: "3002"
