apiVersion: v1
kind: Service
metadata:
  name: notification-manager
spec:
  type: ClusterIP
  selector:
    app: notification-manager
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-manager
  template:
    metadata:
      labels:
        app: notification-manager
    spec:
      containers:
        - name: notification-manager
          image: digital-twin/notification-manager:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: digital-twin-config
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: digital-twin-config
                  key: MONGODB_URI_NOTIFICATIONS
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: digital-twin-config
                  key: MONGODB_DATABASE_NOTIFICATIONS
            - name: KAFKA_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: digital-twin-config
                  key: KAFKA_GROUP_ID_NOTIFICATIONS
            - name: KAFKA_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: digital-twin-config
                  key: KAFKA_CLIENT_ID_NOTIFICATIONS
            - name: API_PORT
              value: "3002"
