apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicles-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicles-monitor
  template:
    metadata:
      labels:
        app: vehicles-monitor
    spec:
      containers:
        - name: vehicles-monitor
          image: digital-twin/vehicles-monitor:latest
          imagePullPolicy: Never
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: digital-twin-config
                  key: KAFKA_BROKERS
            - name: KAFKA_TOPIC_VEHICLES
              valueFrom:
                configMapKeyRef:
                  name: digital-twin-config
                  key: KAFKA_TOPIC_VEHICLES
            - name: KAFKA_GROUP_ID
              value: "vehicles-monitor-group"
            - name: INFLUXDB_URL
              valueFrom:
                configMapKeyRef:
                  name: digital-twin-config
                  key: INFLUXDB_URL
            - name: INFLUXDB_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: digital-twin-config
                  key: INFLUXDB_TOKEN
            - name: INFLUXDB_ORG
              valueFrom:
                configMapKeyRef:
                  name: digital-twin-config
                  key: INFLUXDB_ORG
            - name: INFLUXDB_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: digital-twin-config
                  key: INFLUXDB_BUCKET_VEHICLES
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
